version: "3.9"

services:
  es01-test:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: es01-test
    environment:
      - node.name="es01-test"
      - cluster.name="es-docker-cluster"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - 9300:9200