FROM python:3.10
# 앱 디렉터리 (자동생성)
WORKDIR /app

# 소스 및 설정 파일 추가
COPY ./src /app/src
COPY ./alembic.ini /app/alembic.ini
COPY ./migration /app/migration
COPY requirements.txt /app/requirements.txt

# 앱 의존성
RUN pip install --no-cache-dir -r requirements.txt

# 실행: alembic으로 테이블을 최신화한 뒤 uvicorn 실행
CMD sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 80"
