FROM python:3.10
# 앱 디렉터리 (자동생성)
WORKDIR /app

# 소스 추가
COPY ./src /app/src
COPY requirements.txt /app/requirements.txt

# 앱 의존성
RUN pip install -r requirements.txt

# 실행
CMD [ "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
