version: "3.9"

services:
  backend:
    image: 2jun0/gdet-backend
    container_name: gdet-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    env_file:
      - .env

  db:
    image: mysql:latest
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin