"""0008-ADD-RANK-SCORE-FIELD

Revision ID: 07a7ec136a04
Revises: cc7150130bcf
Create Date: 2024-03-18 17:56:35.329602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '07a7ec136a04'
down_revision: Union[str, None] = 'cc7150130bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_alias', 'game_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('user', sa.Column('rank_score', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rank_score')
    op.alter_column('game_alias', 'game_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
