"""0002-ADD-DAILY-QUIZ-TABLE

Revision ID: 5841362f64f7
Revises: 78fda4736d78
Create Date: 2024-02-12 19:41:05.129500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5841362f64f7'
down_revision: Union[str, None] = '78fda4736d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_quiz',
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('guest_account')
    op.drop_column('quiz_screenshot_link', 'created_at')
    op.drop_column('quiz_screenshot_link', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_screenshot_link', sa.Column('updated_at', mysql.DATETIME(), nullable=False))
    op.add_column('quiz_screenshot_link', sa.Column('created_at', mysql.DATETIME(), nullable=False))
    op.create_table('guest_account',
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('daily_quiz')
    # ### end Alembic commands ###
