"""0003-ADD-DAILY-QUIZ-FEATURE

Revision ID: 5ef83623bd0d
Revises: 5841362f64f7
Create Date: 2024-02-22 02:50:49.146028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5ef83623bd0d'
down_revision: Union[str, None] = '5841362f64f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_quiz', sa.Column('feature', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_quiz', 'feature')
    # ### end Alembic commands ###
