"""0005-REMOVE-GAME-KR-NAME-FIELD

Revision ID: d8e0e8e12a4a
Revises: 5d90f00aa849
Create Date: 2024-03-11 18:08:03.049988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd8e0e8e12a4a'
down_revision: Union[str, None] = '5d90f00aa849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'kr_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('kr_name', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
